練習課題2「正方形を表示させよう」
ryoma-yama/markup_kadai_02 pull request #2
Opened 2020-03-10 08:40 UTC by ryoma-yama

- 間違ってmasterにプッシュしてしまったのでResetしてPRを出し直しました。申し訳ありません。
- b1b47f1 不要ファイルの削除および指摘箇所の修正をしました。

2020-03-26 02:29 UTC, ryoma-yama commented
040a764 にてidをclassにしました

2020-03-31 16:10 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-03-31 16:10 UTC, piasoratech commented on markup_kadai_02.html
> +<html lang="ja">
全体的にインデントをそろえましょう
タグ同士の入れ子を意識すると良いです。

2020-03-31 16:15 UTC, piasoratech approved these changes
OKです！

2020-04-18 00:29 UTC, merged